---
output: word_document
---
**Table S2**. Raw data on the presumed pregnant elk captured from 2006 through 2013. Start and stop dates refer to the dates when the reproductive events occurred. Brucella status of the pregnant female was determined from serological tests interpreted according the USDA methods and rules for cervids. 

```{r rawdata, echo = FALSE, results='asis'}
library(knitr)
opts_chunk$set(dev = "png", dpi = 400, echo = FALSE, message = FALSE)
```

```{r TableS2, fig.height = 7, fig.width = 5, echo = FALSE, fig.cap= "", fig.lp=""}
rm(list = ls())
setwd("~/BitBucket/VIT2014/Analysis")
library(knitr)
library(lubridate)
RawData <- read.table("VIT_Data2014.txt", sep="", header=T) #load in data
RawData <- RawData[order(RawData$CaptureDate), c(1,2,5,6,7,9,11, 13)]
names(RawData) <- c("ElkID", "Feedground", "Captured", "Event.Start", "Event.End", "Event.Type", "Mom.Brucella", "Recovered")

#recode some of the elk lingo
levels(RawData$Event.Type) <- c("Abortion", "Death", "Malfunction", "NotPregnant", "Birth", "*")

#reformat the dates
RawData[,3] <- as.character(mdy(RawData[,3]))
RawData[,4] <- as.character(mdy(RawData[,4]))
RawData[,5] <- as.character(mdy(RawData[,5]))
RawData[,8] <- as.character(mdy(RawData[,8]))
RawData[,7] <- as.character(RawData[,7])
RawData <- RawData[order(RawData$ElkID),]

#Fill in the NAs for knitr
tmp <- which(is.na(RawData[,4]) == T)
RawData[tmp, 4] <- "*"
tmp <- which(is.na(RawData[,5]) == T)
RawData[tmp, 5] <- "*"
tmp <- which(is.na(RawData[,7]) == T)
RawData[tmp, 7] <- "*"
tmp <- which(is.na(RawData[,8]) == T)
RawData[tmp, 8] <- "*"
row.names(RawData) <- 1:nrow(RawData)
kable(RawData, format='markdown', row.names = NA)
```
