---
output: word_document
---
Jan 13, 2015    
Paul C. Cross  
2327 University Way, Suite 2  
Bozeman MT 59715  
Phone: 406/994-6908; Fax: 406/994-6556  
Email: pcross@usgs.gov     

RH: Cross et al. Cause-specific hazards 

**Estimating the phenology of elk brucellosis transmission with hierarchical models of cause-specific and baseline hazards**  

PAUL C. CROSS, *U.S. Geological Survey, Northern Rocky Mountain Science Center, Bozeman MT, 59715 USA*  
ERIC J. MAICHAK, *Wyoming Game and Fish Department, Pinedale WY, 82941 USA*  
JARED D. ROGERSON, *Wyoming Game and Fish Department, Pinedale WY, 82941 USA*  
KATHRYN M. IRVINE, *U.S. Geological Survey, Northern Rocky Mountain Science Center, Bozeman MT, 59715 USA*  
JENNIFER JONES, *U.S. Geological Survey, Northern Rocky Mountain Science Center, Bozeman MT, 59715 USA*  
DENNIS M. HEISEY, *U.S. Geological Survey, National Wildlife Health Center, Madison WI, 53711 USA*  
WILLIAM H. EDWARDS, *Wyoming Game and Fish Department, Laramie WY, 82070 USA*  
BRANDON. M. SCURLOCK, *Wyoming Game and Fish Department, Pinedale WY, 82941 USA*    
\newpage

**ABSTRACT**
Understanding the seasonal timing of disease transmission can lead to more effective control strategies, but the seasonality of transmission is often unknown for pathogens transmitted directly. We inserted vaginal implant transmitters (VITs) in 575 elk (*Cervus canadensis*) from 2006 to 2014 to assess when reproductive failures (i.e., abortions or still births) occur, which is the primary transmission route of *Brucella abortus*, the causative agent of brucellosis in the Greater Yellowstone Ecosystem. Using a survival analysis framework, we developed a Bayesian hierarchical model that simultaneously estimated the total baseline hazard of a reproductive event as well as its two, mutually-exclusive, parts (abortions or live births). Approximately 16% (95% CI = [0.10, 0.23]) of the pregnant seropositive elk had reproductive failures, while 2% (95% CI = [0.01, 0.04]) of the seronegative elk had probable abortions. The timing of events was known only to an interval, but reproductive failures could have occurred as early as January 22nd and as late as July 10th, peaking from March through May. Model results suggest that less than 5% of likely abortions are occurred after June 6th each year and abortions were approximately five times more likely in March, April or May compared to February or June. In western Wyoming, supplemental feeding of elk begins in December and ends during the peak of elk abortions and brucellosis transmission (i.e., March and April). Years with more snow may enhance elk-to-elk transmission on supplemental feeding areas because elk are artificially aggregated for the majority of the transmission season. Elk-to-cattle transmission rate will depend on the transmission period defined here, as well as elk seroprevalence, population size, and the amount of commingling during the transmission season. Our statistical approach allowed us to estimate the probability density function of different reproductive event types over the course of a year, which may be generally applicable to other cause-specific survival analyses. 
 
**KEY WORDS** *Brucella abortus*, Greater Yellowstone Ecosystem, survival analysis, time to event, wildlife disease, vaginal implant transmitter
  
Seasonal peaks in disease transmission are typical of many vector-borne and environmentally transmitted infections [@Altizer2006]. In the absence of a temperature or moisture-dependent vector, however, it is difficult to know when disease transmission occurs, particularly for chronic infections without obvious signs. Understanding the seasonal timing of transmission can allow for more targeted control strategies (e.g., vector control or maintaining spatial separation between host species) during the key time periods [@Altizer2006; @Kilpatrick2009].   

Brucellosis, caused by the bacterium *Brucella abortus*, is a major management issue around the Greater Yellowstone Ecosystem (GYE) due to the potential for transmission from elk (*Cervus canadensis*) or bison (*Bison bison*) to cattle. The cattle populations of most states in the USA are brucellosis-free [@Ragan2002], with the exception of Idaho, Montana and Wyoming where there have been an increasing number of infections despite high vaccination coverage in cattle [@Rhyan2013]. Meanwhile, *B. abortus* appears to be expanding into new elk populations [@Cross2010].  

*B. abortus* typically causes a pregnant animal to have a reproductive failure (i.e., abortion or stillbirth), and physical contact with the aborted fetus is the primary route of transmission [@Cheville1998]. Therefore, preventing spatial overlap of elk with livestock during the abortion period is often considered the most effective management strategy to reduce cattle exposure. In captive studies of elk, *Brucella*-induced abortions occurred during the third trimester of pregnancy, which is March through May in this region [@Thorne1978a; @Roffe2004]. As a result, elk and bison are hazed off of cattle properties from late winter through early spring in some regions of the GYE to minimize possible cross-species transmission [@Jones2010]. In addition, adjusting the date that cattle are moved to federal grazing allotments in summer can also affect the amount of elk-cattle comingling. However, the relative transmission risk of commingling during June compared to March, for example, is unknown, in part because abortions are rare and difficult to observe in field settings.   

State and Federal managers in western Wyoming provide supplemental hay during the winter to around 24,000 elk at 23 sites. The increased aggregation caused by the feeding program promotes elk contact and disease transmission [@Maichak2009; @Creech2012], but reduces commingling between cattle and elk during the feeding season. Thus, understanding how changes to the feeding program may affect elk-to-elk and elk-to-cattle transmission depends upon the seasonal timing of elk abortions. In this study, we compared data on when fetuses were recovered from feedgrounds opportunistically (1969 to 2014) with an analysis of over 500 pregnant elk that were fitted with vaginal implant transmitters (VITs) to determine when abortions occurred. 

Disease, survival, and pregnancy data have similar characteristics when the outcome of interest is frequency or timing of the event. We can equate time until death in a survival context with time until infection or birth in a disease or pregnancy context, respectively. These data can be statistically challenging due to left-truncation, interval and right-censoring. Here we borrow from the survival analysis literature to estimate the timing and frequency of reproductive events during a season. We then partition the event type using a cause-specific hazard framework. In this case, our two competing risks are abortion and live birth, rather than hunting or natural mortality, for example, in a survival analysis. This combined model allows us to estimate the timing of the transmission season for *B. abortus* in this region.  

Cox proportional hazards (CoxPH) models are commonly used to estimate the relative risk of death by comparing the covariates associated with the individuals that die to the other subjects that were at-risk [@Cox1972; @Fieberg2009a]. The underlying baseline hazard of mortality is removed from the model by focusing on the relative risk (via a partial likelihood). Here the baseline hazard refers to the instantaneous rate of an event occurring. Removing the baseline is useful in some applications (e.g., medical treatment trials) because the time-varying baseline hazard may be difficult to model parametrically and is more of a nuisance to control for rather than the primary interest. In this study, however, the baseline hazard of when reproductive events occur is of direct interest, and is required to estimate the probability density function of events over time rather than just the instantaneous hazard. As Fieberg and DelGiudice [-@Fieberg2009a] note, one can use different timescales (e.g., age, calendar time, and day of year) to establish Cox PH risk sets, and hence, redefine the baseline hazard. However, one cannot investigate multiple time scales simultaneously. Further, covariate effects that vary over time are problematic due to the proportionality assumption [@Zucker1990; @Grambsch1994]. 
  
In addition to estimating the baseline hazard, we also have a problem of competing risks whereby females can end their pregnancy in one of two ways (abortion or live birth). These mutually exclusive reproductive event types are similar to cause-specific mortality analyses in which individuals can die from different causes [e.g., road accident versus disease, @Lebreton2005]. A common approach is to censor the records of events due to causes other than the one of interest [@Kalbfeisch1980], which assumes that failures due to those other causes are not informative. As an alternative, Lunn and McNeil [-@Lunn1995] proposed an augmented data approach whereby the failure type is included as a covariate in a CoxPH model. However, with the CoxPH model we have lost the ability to look at the baseline hazard, and we must assume that the relative risks are proportional to one another over time.   

Here, we describe the timing of *Brucella*-induced abortions from the use of VITs and recovery of aborted fetuses from feedgrounds. Then based on those empirical data, we illustrate how to estimate both the total hazard of an event and partition that hazard into its cause-specific components using a hierarchical Bayesian approach. In our example, we equate pregnancy with survival. All individuals enter the study as pregnant (i.e., alive) and exit the analysis (i.e., die) when a birth or abortion event occurs. Our approach is generalizable to survival analyses so we use this equivalence in our initial mathematical formulation. We contrast our approach with a more typical approach of censoring all the events that are not of interest, and discuss how our methodology helps define the seasonal timing of different event-types. We end with a discussion of how these results relate to intra- and interspecific brucellosis transmission risk associated with elk.

**STUDY AREA**  
We monitored elk across the western Wyoming area of the Greater Yellowstone Ecosystem (GYE) where the elevations ranged from around 1000 to 4200 m and landownership was a mixture of private, State, Bureau of Land Management, US Forest Service, and US National Park property (Figure 1). Vegetation at lower elevations was typified by sagebrush (*Artemisia spp.*) communities, transitioning to lodgepole pine (*Pinus contorta*), Douglas fir (*Pseudotsuga menziesii*), and aspen (*Populus tremuloides*) at mid-elevations, and spruce (*Picea engelmannii*) and subalpine fir (*Abies lasiocarpa*) at upper elevations. Around the supplemental feeding grounds vegetation was dominated by a few grass (*Bromus inermis*, *Agropyron christatum*) and forb (*Descurania pinnata*, *Polygonum douglasii*) species.  

**MATERIALS AND METHODS**  

**General Survival Case**  

The conditional survival function from day *r* to *s* can be estimated as  

[1]$$S(s|r) = exp \left(- \int_r^s h(u)du \right) \approx exp \left(- \sum_{k=r}^s exp(\phi_k) \right)$$ 

where $h(u)$ is the mortality hazard at time *u* and $\phi_k$ is the log cumulative hazard on day *k* assuming a piecewise constant hazard [@Heisey2010]. Few datasets will support the independent estimation of daily hazards. To resolve this issue we 'borrow strength' from neighboring days on the assumption that the underlying biological hazard is not too different from one day to the next. We used two approaches for smoothing the daily hazards. First we used a first-order conditional autoregressive (CAR) approach whereby $\phi_k = \phi_0 + \theta_k$ and $\theta_k \sim Normal(\theta_{k-1}, \sigma^2)$. Here $\sigma^2$ controls the relative smoothness and is also estimated from the data. On sparse datasets, the CAR model can be slow to converge, so we also used a penalized spline approach of Crainiceau *et al* [-@Crainiceanu2005] as a comparison which had better mixing properties on MCMC chains. We chose 10 and 40 knots for the penalized spline to create relatively stiffer or more flexible models, respectively.   

Let $h_c(t)$ be the cause-specific hazard of cause *c* and 

[2]$$S_c(t) = exp \left(-\int_0^t h_c(u)du \right)$$

and $h(t)=\sum_1^C h_c(t)$, where *C* is the total number of possible causes of death. Note that although overall survival $S(t) = \prod_{c=1}^C S_c(t)$, $S_c(t)$ itself does not have a meaningful biological interpretation and the cumulative cause-specific mortality $M_c(t)$ does not equal $1-S_c(t)$ [@Heisey2006]. Instead 

[3]$$M_c(t) = \int_0^t h_c(u)S(u)du$$

which accounts for the censoring due to other causes of mortality [@Heisey2006]. With a hierarchical modeling approach, we can partition $h(t)$ into its constituent parts. For the case with two mortality types (e.g., natural and anthropogenic), we could use logistic regression to estimate the covariates associated with mortality being more likely to be of one cause than another or how partitioning of the hazard changes through time. Multinomial regressions may be appropriate for scenarios with three or more mortality types. We develop this approach below using data on elk reproductive events that are due to two different causes. 

Managers and researchers may be interested in estimating when events are likely to occur rather than the hazard of an event given it has not yet occurred. This is the difference between the probability density function or event density $f(t)$ and the hazard $h(t)$, respectively. The event density equals the survival function $S(r)$ times the hazard function $h(t)$. In a cause-specific mortality the event density of a specific cause is $f_{c=1}(t) = h_{c=1}(t)S(t)$ or $p(t)h(t)S(t)$. Estimating $f_{c=1}(t)$ and its precision is difficult in some survival analyses because one needs to estimate both the cause-specific hazard $h_{c=1}(t)$ and $S(t)$, but the latter depends on other possible mortality types, which are often censored from the dataset.

**Elk Pregnancy Data**  
During January through March of 2006-2014 we captured 575 adult (>1 year old), female elk from feedgrounds and adjacent native winter ranges in the Lincoln, Sublette, Sweetwater and Teton counties of Wyoming, using corral traps, ground darting, and net guns (Fig. 1, Table S1). We used a portable ultrasound (E.I. Medical Imaging, Loveland, CO, USA) to determine pregnancy and implanted VITs (Advanced Telemetry Systems, Isanti, MN, USA) in pregnant elk. Misclassified non-pregnant elk, as determined by blood tests [@Noyes1997],  were removed from the analyses. We used 43-g VITs and followed the method of Johnson *et al*. [-@Johnson2006] for implantation. All procedures were approved by the the Montana State University and Iowa State University animal use and care protocols (#2010-02, #8-05-5962). Births or reproductive failures result in VIT expulsion and the temperature change initiates a change in the VIT signal from 40 to 80 beats-per-minute [@Barbknecht2009]. To supplement our VIT analyses, we collected records of dates that fetuses were observed on the supplemental elk feedgrounds from 1968 to 2014. Although this is an opportunistic sample of reproductive failures, feeders are on-site daily during the supplemental feeding season. 

We monitored VITs daily from the ground while elk remained on the feedgrounds, and then every three to seven days after the feeding ended until they could no longer be found or accessed. We conducted aerial flights every five days from mid-May until mid-June and then every seven days thereafter until all VITS were accounted for. Some flights had to be adjusted or canceled due to weather. With this sampling intensity over half of the VITS were found within three days of when they were known to be expelled. 

We classified events as regular births when we observed a location exhibiting  typical birth site characteristics [e.g., matted and/or eaten vegetation, moist soil, fresh feces, elk odor, ants and/or flies, lack of fetus or fetal remains; @Barbknecht2009] during the typical birth season [mid-May through late June; @Barbknecht2011]. We classified an event as a reproductive failure when we found a fetus or partial remains; we isolated *Brucella* by culturing or PCR; and/or we recovered the VIT outside of the typical birthing season [@Barbknecht2009]. All of these criteria were considered in concert with one another and none were considered definitive with the exception of finding the fetus or partial remains. The date of a reproductive event was determined by a precise event timing (PET) device which activated once a VIT switched to 80 bpm and indicated the time of expulsion within 30 minutes [@Barbknecht2009]. Events that occurred later in the year during warmer ambient temperatures and/or VITs that were exposed to direct sunlight for prolonged periods of time did occasionally switch back to 40 bpm, giving the impression that the VIT was still inside the elk and rendering the PET code unreliable. In addition, the PET code has a maximum coded time signal of 5.3 days. In these cases, we used an event interval starting with the last date the VIT was heard at 40bpm to the first date it was heard at 80bpm. For elk with GPS collars we compared the GPS locations with the location of the recovered VIT to ascertain an exact date or a shorter time interval for the reproductive event. In many cause-specific mortality studies, the cause is not known with certainty [e.g., @Etterson2008]. The same is true in this study where some events classified as live births may have been abortions instead. The infectiousness of live births from infected elk is unknown. For this reason we present results on the timing of both the probable abortion and live birth events. We address the importance of possible misclassifications in the discussion. 

We restricted most of our statistical analyses to brucellosis seropositive elk because the cumulative abortion hazard will likely increase with seroprevalence. As a first approximation, our abortion hazards can be extrapolated to other areas via multiplying by the seroprevalence of those regions. This assumes that the disease is at equilibrium and abortion rates are constant from year to year given the seroprevalence, which may be a reasonable assumption for the feedgrounds but less likely for other regions where brucellosis appears to be invading. When the disease is increasing over time, a higher fraction of individuals will be newly infected and thus more likely to have an abortion [@Thorne1978a; @Cheville1998]. To assess whether the inclusion of seronegative elk affected the time period of abortions we also conducted some analyses with all individuals. About 10% of individuals were monitored in more than one year, but we assumed their reproductive events were independent samples from one year to the next.  
 
We assessed *Brucella* status using the card test, plate agglutination, rivanol precipitation-plate agglutination, and complement fixation serological assays [@Scurlock2010]. Reactors were those animals with positive card tests, rivanol incomplete at 1:25 or higher, CF of 2+ at 1:20 or higher, and SPT positive at 1:25 or higher. Most elk visiting the feedgrounds have been vaccinated as juveniles using biobullets with Strain 19, but this does not appear to produce positive antibody tests the following year. Serological profiles were categorized as positive or negative using the United States Department of Agriculture's brucellosis eradication uniform methods and rules for cervids (APHIS 91-45-013). 

**Statistical Analysis**  

Let $y_{ij}$ represent the data on reproductive events (still pregnant = 1, no longer pregnant = 0) of individual *i* (Fig. 2). Time intervals over which reproductive events are either known to occur (*j*=1) or known not to occur (*j*=2) start at $r_{ij}$ and end at $s_{ij}$. Individuals have only one record and *j* = 2 if they were censored due to death. If the reproductive event occurred between the capture date and the first recorded follow-up then there is no *j* = 2 record.   

We model each reproductive event as a conditionally independent Bernoulli trial such that  
[4]$$y_{ij} \sim Bern \left(exp \left(- \sum_{k=r_{ij}}^{s_{ij}} exp(\phi_k) \right) \right)$$,  
where $\phi_k$ is the log of the cumulative hazard of any reproductive event for time period *k*. Let $z_i$ represent the data on the type of reproductive event (i.e., the two competing risks; 0 = live birth, 1 = abortion). We estimated the probability that an event was an abortion using a generalized logistic function that allowed for a lower asymptote: $z_i \sim Bern \left(p_i \right)$, and  
[5]$$p_i = 1 + \frac{\kappa-1}{1+exp\left(- \alpha -\beta \left(s_{ij} | y_{ij}=0 \right)\right)}$$ 
where $p_i$ is the probability of an abortion for individual *i* given the event occurred by day of year *s*. The lower asymptote, $\kappa$, allowed for there to be a small chance of an abortion event even late in the year after many births have occurred. Elk are seasonal breeders so reproductive failures are likely to occur earlier in the year than live births; $\alpha$ and $\beta$ determine how quickly reproductive events transition from reproductive failures to births (for model code see Appendix S1). We also explored models without a lower asymptote that were simple logistic regressions of the probability of abortion (data not shown).  

The joint data likelihood was $L\left(y_{ij}, z_i | s_{ij}, r_{ij}, \phi_k, \alpha, \beta, \kappa \right) = L\left(y_{ij}|s_{ij}, r_{ij}, \phi_k) L(z_i| y_{ij}, s_{ij}, \alpha, \beta, \kappa \right)$. We estimated the posterior distribution of model parameters using Bayesian estimation via Markov chain Monte Carlo (MCMC) and Just Another Gibbs Sampler [JAGS, @Plummer2003] launched from R version 3.1 [@RDevelopmentCoreTeam2014]. We used the following prior distributions: $\alpha \sim U(50, 200)$, $\beta \sim U(0, 2)$, $\kappa \sim U(0, 0.5)$, $\phi_0 \sim N(0, 10^6)$, which assumes that reproductive failures tend to occur before births with respect to day of year, but are otherwise relatively non-informative. For the CAR smoothing we assumed $\theta_1 \sim N(0, 10^6)$, $\theta_{k=2:K} \sim N(\theta_{k-1}, \sigma^2)$, $\sigma \sim U(0,10)$, which are also relatively uninformative. 

We used the approach of Crainiceau *et al.* [-@Crainiceanu2005] for the penalized splines, where $\phi_k = \phi_0 + \textbf {Z}b_n$, $b_n$ is a vector of random coefficients for the *n* knots (10 or 40) with prior distributions of $b_n \sim N(0, \sigma_b^2)$ and $\sigma_b \sim U(0,3)$ and $\textbf{Z}$ represents a design matrix (Appendix S1). Once we have estimated these parameters we can then derive $p(t)$. Assuming that $\phi_k$ is a good approximation of $log(h(t))$ we can estimate the cause-specific hazard of a reproductive failure (*c*=1) as $h_{c=1}(t) = p(t) h(t)$ and the hazard of a normal birth as $h_{c=2}(t) = \left(1-p(t) \right) h(t)$. For comparison, we also estimated $h_{c=1}(t)$ using a dataset where all live births are removed, in which case $h_{c=1}(t) = h(t)$ and the partitioning of event types is removed from the model.  For each model, we ran three chains of 500,000 iterations and a burn-in period of 250,000 iterations. We checked convergence visually by assessing sample trace plots and by calculating the potential scale reduction factor to compare within- and among-chain variance, where values of 1 to 1.1 typically indicate convergence [@Gelman2007]. 

**RESULTS**
```{r setup, echo = FALSE}
setwd("~/BitBucket/VIT2014/Analysis")
rm(list = ls())
library(knitr)
library(lubridate)
Data <- read.table("VIT_Data2014.txt", sep="", header=T) #load in data
load('VIT_Data2014_Full_POS.RData')
load('Result_mod40k1.RData')

```
Among 575 female elk captured, 165 were seropositive and we documented 30 reproductive failures that occurred from February 14th at the earliest to July 10th at the latest (Fig. S1). Twenty-one females were found to be not pregnant on follow-up blood tests. Two VITs malfunctioned and 52 were not recovered. The analyzed dataset consisted of 498 individuals, of which six died prior to calving. Seropositive individuals were more likely to have a reproductive failures (proportion aborting = 0.16, 95% CI = [0.11, 0.23]), than seronegative individuals (proportion aborting = 0.02, 95% CI = [0.01, 0.04]). For the seropositive elk dataset, we had `r dim(TypePOS)[1]` reproductive events and `r length(unique(TypePOS$Elk_ID))` unique individuals, some of which were caught in multiple years (Fig. 2A). There was one outlier abortion that occurred after July 1st that was included in all analyses. Wyoming Game and Fish Department (WGFD) records noted 79 fetuses that were opportunistically observed from February 2nd to May 10th during 1968-2014 on the supplemental feeding grounds(Fig. 2B). 

All the smoothing models had similar predictive power based upon deviance information criterion (DIC, Table 1), and hazard estimates were similar (Fig. S2), so we present only the 40-knot spline model in the main text. Abortion hazards were relatively similar between the models where births were censored compared to the full models with births and abortions included (Fig. 3). However, the models that partition the hazard, rather than censoring the live births, allowed us to estimate how the probability an event was an abortion changed through time (Fig. 4) as well as the abortion and birth densities (Fig. 5). The probability a reproductive event was an classified as an abortion declined rapidly from 98% on May 1st to less than a 5% chance of it being an abortion after May 23rd (Fig. 4). The lower asymptote, $\kappa$, for the probability a reproductive event was an abortion event was `r round(mod40k$BUGSoutput$mean$K,2)` (95% CI = [`r round(quantile(mod40k$BUGSoutput$sims.list$K, c(0.025, 0.975)),2)`]) for all models. 

The event density $f(t)$ and the hazards of an event given that it has not yet occurred $h(t)$ can be very different (Fig. 5). For example, the hazard of having a live birth remains high through July (Fig. 5C) even though most births occur around the 1st of June (Fig. 5D). For models that partitioned the hazard, 95% of probable abortions are likely to occur prior to the 2nd to 4th of June, and 75% probably occur before 6th to 9th of May (Table 1). 

**STOPPED HERE**
There was a bimodal pattern of abortion densities in March and May (Fig. 5A, B and Fig. S2).  

We calculated the expected number of abortions from 100 seropositive elk by summing the area under the curve of the abortion density $f_{c=1}(t)$ and multiplying by 100 (Table 2). Abortions were roughly five times more common during March, April or May compared to either February or June (Table 2). By limiting most of our analyses to brucellosis seropositive elk we removed eight of the 30 total abortions in the VIT dataset. When these are included 75% and 95% of reproductive failures are likely to have occurred before the 15th of May and the 5th of June, respectively (Table S2, Fig. S3). 

**DISCUSSION**  

Using a hierarchical Bayesian approach we simultaneously estimated total and cause-specific hazards over time while accounting for interval-censoring, left truncation and right-censoring. This method allowed us to  estimate the density of abortion events over time, rather than the hazard, while accounting for other event types. Elk abortions, the primary transmission route of *Brucella abortus*, were concentrated between March and May. We estimated that 95% of likely elk abortions occurred prior to the 5th of June in this region, and abortions are about five to six times more common in March, April and May compared to February or June.We believe the probability density function of abortion events over time is a useful metric for managers working on minimizing the potential for elk to cattle transmission. 

The non-parametric pattern of abortion hazards and densities over time (Fig. 5, Fig. S3) is one of the reasons why Cox PH models are used. When the baseline hazards are not of direct interest it is easier to remove them and focus on covariate effects. In our case, however, the temporal fluctuations were our primary interest. The May peak in abortions may be a model artifact whereby the total reproductive event hazard increased in mid May due to live birth events and is only later counteracted by the decreasing probability that the event is an abortion (Fig. 4, 5). Assessing how changes in the hazard of one event-type may affect the estimation of another is an important avenue for future research using this methodology. Alternatively, the two peaks in the abortion density may have a biological explanation. Some elk may become infected early in the winter and then abort later that same year in May; while others that were infected in April and May may have an abortion early the following year in March. Our model estimates and the opportunistically collected fetuses from feedgrounds both indicate that abortions begin in February and continue through early May. The opportunistic data on abortions in late spring are probably biased, however, because elk feeders do not make daily visits to feedgrounds once the elk disperse. 

In our assessment of brucellosis transmission, we did not address the influence of snowpack, persistence of *B. abortus* in the environment, or shedding of the bacteria post-abortion. In this region, snowpack drives the length of the supplemental feeding season [@Cross2007c]. In years with more snow, such as 2011, the average end of the feeding season was the 17th of April. In years with less snow, like 2010 and 2012, the average end of the feeding season was March 30th, at which point only about 40% of the abortions for that year have occurred. Thus, years and sites with more snow are likely to have more elk-to-elk transmission due to longer duration of high elk aggregation throughout the transmission season. In years with less snow and shorter feeding seasons the risk of brucellosis transmission to cattle will depend upon the extent of elk and cattle co-mingling during the time period after elk disperse from feedgrounds.

*B. abortus* can persist in the environment for several weeks [@Cook1999; @Aune2012], and vaginal exudates of infected cow elk contain *B. abortus* for up to 17 days following abortion [@Thorne1978a]. Environmental persistence of *B. abortus* is likely to be driven by the scavenging rate of fetuses and abiotic conditions at the time of abortion. In areas distant from feedgrounds, Aune *et al* [-@Aune2012] found that fetuses disappeared on average within 18 days, but on the feedgrounds fetuses tend to be removed by scavengers within two days [@Maichak2009; @Cook2004]. By adding the median environmental bacterial lifespan in May [13 days, @Aune2012], or the 17 days of potential post-abortion bacterial shedding to the 95th percentile of the cumulative abortion density we can approximate that less than 2.5% of all potential elk brucellosis transmission is likely to occur after the 22nd of June. Even though our results suggest that cattle risk may be very low after May, our empirical data show that reproductive failures do occur as late as July 9th. A single contact with a contaminated fetus is sufficient to expose a cattle herd. We suggest that land and livestock managers in the GYE review site-specific information of elk space-use during the transmission risk period, which we helped to define here, to identify and avoid areas of high risk. 

We found that live births were concentrated around June 1st, consistent with previous findings [@Barbknecht2011]. By labeling abortions as the transmission period we are assuming that normal births are not infectious and that they were not misclassified. Misclassification may occur because we were aware of the date as we investigated the VIT expulsion sites and this may have biased our assessment towards classifying events later in the year as normal births. Thus underestimating the abortion rate in the later part of the year. Thorne *et al.* [-@Thorne1978a] documented shedding of *B. abortus* up to nine days after a normal birth and we have detected *B. abortus* on VITS from probable live births. Nonetheless, we believe that live births or late-season abortions are less likely to result in transmission. Abiotic factors during the calving season are not as favorable for environmental persistence of *B. abortus* [@Aune2012], and elk having live births tend to seclude themselves as a predator avoidance strategy [@Geist2002; @Barbknecht2011], thus minimizing contact. Based on observations of elk feeders and WGFD personnel, elk do not appear to seclude themselves during abortion events as would be typical for live births. In addition, proximity collar data from elk show low elk-to-elk contact rates in June [@Cross2013b]. Thus, even if live births are infectious the contact rate with those live births is likely to be low. Managers and ranchers would prefer zero risk of transmission from elk to cattle, but this would require complete separation at least through June. We believe that is unlikely and the relative costs and benefits must be weighed. 

The hierarchical approach that we develop here has potential applicability to many wildlife survival studies, and could be extended in several ways. First, one could incorporate classification uncertainty [@Etterson2008]. In addition, it could be extended to include covariates at different levels of the model hierarchy. For example, individual (e.g., sex and age) or environmental (e.g., region, habitat) covariates may be predictive of a specific cause of mortality, but only weakly associated with overall mortality, particularly if that cause-specific mortality hazard is lower than others. Also, covariates may have varying impacts upon different cause-specific mortalities, which may cancel each other out in a total mortality analysis. Our approach could be expanded to time-varying covariate effects as well, something that is problematic in a Cox PH model [@Grambsch1994]. This model also may be relevant to work on compensatory versus additive mortality induced by hunting. This can be assessed statistically through the correlation of the cause-specific hazards [@Schaub2004; @Servanty2010]. Ideally one might estimate the cumulative hazards over some period of time and then assess the correlation between the cumulative hazards. However, it is not obvious what the appropriate time periods are and what the time lag might be for one cause-specific hazard to respond to another.

**MANAGEMENT IMPLICATIONS**  

Our results suggest that brucellosis transmission risk from elk in western Wyoming is probably highest from March through May, assuming that reproductive events later in the season where elk go into seclusion and consume the afterbirth are unlikely to result in transmission. The average end of the feeding season extends to March 30th in years with less snow and into mid-April during high snow years. Elk are spatially separated from cattle during the feeding season, but once elk move off the feedgrounds managers have limited control over their distribution. Our results suggest that managers should continue to minimize elk concentrations on feedgrounds to reduce intraspecific transmission opportunities, which will indirectly reduce interspecific transmission risk to cattle. To reduce cattle risk during the later portion of the risk period, managers should coordinate with livestock owners and regulatory livestock health officials to assess areas where transmission events may be more likely. Our estimates on the seasonal timing of abortions, combined with information about where elk are at these times will allow managers to more accurately assess areas of high risk for likely abortion events and develop mitigation efforts. 

**ACKNOWLEDGMENTS**  

We thank P.J. White, S. Cubaynes, and several anonymous reviewers for their comments on earlier versions of this paper, J. Jennings-Gaines and H. Killion for serologic testing, D. Stinson and T. Schell for aerial flights. J. Henningsen, A. Barbknecht, L. Linn-Meadows, W.S. Fairbanks, K. Belinda, C. Hansen, D. Damm, J. Brown, C. Brown, E. Tooker, B. Wise, K. Campbell, D. Clark, B. Lozier, T. Peden, B. Klareen, T. Haverberger, J. Schmidt, M. Shaffer, B. King, and many others assisted with VIT monitoring and retrievals. This work was supported by the Wyoming Wildlife-Livestock Disease Partnership, Morris Animal Foundation, Rocky Mountain Elk Foundation, The American Museum of Natural History's Theodore Roosevelt Memorial Fund, Iowa State University, National Science Foundation and National Institutes of Health Ecology of Infectious Disease Grant DEB-1067129, Wyoming Game and Fish Department, and U.S. Geological Survey. Any use of trade, product, or firm names is for descriptive purposes only and does not imply endorsement by the U.S. Government. 

**LITERATURE CITED**  

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
